services:
  - type: web
    name: hate-speech-api
    runtime: python
    runtimeVersion: 3.11.9
    plan: free
    region: us-east
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT run_backend:app
    envVars:
      - key: DATABASE_URL
        scope: build,run
        sync: false
      - key: SECRET_KEY
        scope: build,run
        sync: false
      - key: JWT_SECRET_KEY
        scope: build,run
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        scope: build,run
        sync: false
